jobs:
- name: Build-php-img
  public: true
  serial: true
  plan:
  - aggregate:
    - get: cflinuxfs2-php-git
    - get: cflinuxfs2-image
      params:
        save: true
    - get: php_buildpack
      version:
        tag: v4.3.14
  - task: merge-dir
    file: cflinuxfs2-php-git/ci/merge-dir/merge-dir.yml
  - put: cflinuxfs2-php-image
    params:
      build: php_plus_dockerfile/
      load_base: cflinuxfs2-image
      tag: php_plus_dockerfile/php_buildpack/version



resources:
- name: php_buildpack
  type: github-release
  source:
    user: cloudfoundry
    repository: php-buildpack
    access_token: {{github-access-token}}


- name: cflinuxfs2-php-git
  type: git
  source:
    branch: master
    private_key: {{private-key-github-concourse}}
    uri: git@github.com:shinji62/cflinuxfs2-php-buildpack-image.git


- name: cflinuxfs2-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2

- name: cflinuxfs2-php-image
  type: docker-image
  source:
    repository: getourneau/cflinuxfs2-php
    email: {{email-docker-hub}}
    username: {{username-docker-hub}}
    password: {{password-docker-hub}}



